spring:
  application:
    name: smarthome

server:
  port: 8080

mqtt:
  broker-url: tcp://127.0.0.1:1883
  client-id: stm32_zpf
  topic: access_control,bedrom,kitchen,living_room,toilet
  username: admin
  password: a12345678