spring:
  application:
    name: smarthome

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smarthome?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: test  # 替换为你的 MySQL 用户名
    password: 123456 # 替换为你的 MySQL 密码
    # JPA 配置
  jpa:
    hibernate:
      ddl-auto: update  # 自动创建/更新表结构（
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 方言

server:
  port: 8080

mqtt:
  broker-url: tcp://127.0.0.1:1883
  client-id: kang
  topic: access_control,bedrom,kitchen,living_room,toilet
  username: admin
  password: a12345678

jwt:
  secret: 345462
  expiration: 3600000

