spring:
  application:
    name: smarthome
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smarthome?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    # JPA 配置
  jpa:
    hibernate:
      ddl-auto: update  # 自动创建/更新表结构（
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 方言

server:
  port: 8443
  ssl:
    key-store: classpath:mykeystore.p12
    key-store-type: PKCS12
    key-alias: mycert
    key-store-password: 123456
  servlet:
    session:
      cookie:
        http-only: false
        same-site: none
        secure: true
        max-age: 86400
      timeout: 86400s


mqtt:
  broker-url: tcp://8.156.86.179:1883
  #broker-url: tcp://8.156.86.179:1883
  client-id: kang
  topic: toilet,kitchen,access_control,access_control_cmd,living_room,bedroom,water_pump_1_status,temp_and_hum_1,led_1_status,shower_room_status,smart_ac
  username: jiaju
  password: A12345678

Xliat:
  appid: 0c08f010
  apiKey: 21d4ab35c18240e5c37c5b7aaa422c21
  apiSecret: Y2Y2OWRkYjJmZTdmYTY1ZTY3YWU5NzVi
ai:
  api:
    password: sTXfJZJuAnDbwOhQxuGV:kVZLpvmzpurZaxLyxfbw

