# ??????
spring:
  application:
    name: mqttdemo  # ?????????????????

# ???????
server:
  port: 8080  # ??????????

# MQTT ?????? properties ?? mqtt.xxx ????? mqtt ????
mqtt:
  broker-url: tcp://127.0.0.1:1883  # MQTT ???????
  client-id: stm32_zpf  # MQTT ????????????????????
  topic: bedroomTopic,toiletTopic  # ?????????????????
  username: admin  # MQTT ?????????????????????
  password: a12345678  # MQTT ?????????????????